import { useMemo, useState } from 'react'
import { IconCalendarStats as CalendarRange, IconChevronLeft as ChevronLeft, IconChevronRight as ChevronRight, IconPlus as Plus, IconSearch as Search, IconX as X } from '@tabler/icons-react'
import { Card, Input, MoneyInput } from '../components/ui'
import { Currency } from '../components/Currency'
import { brl, cn, fluxMeta, money, monthKey, saldoTemperature, uid } from '../lib/utils'
import { useFinancas } from '../store/use-financas'
import type { FluxTipo } from '../lib/types'

type FluxTab='saldos'|'totais'|'tags'|'menu'
export function Flux(){
 const {data}=useFinancas(); const [monthOffset,setMonthOffset]=useState(0); const [tab,setTab]=useState<FluxTab>('saldos');const [horizon,setHorizon]=useState(false);const [adding,setAdding]=useState(false)
 const base=new Date(2026,6+monthOffset,1);const key=monthKey(base);const label=new Intl.DateTimeFormat('pt-BR',{month:'short',year:'2-digit'}).format(base).replace('.','')
 return <div className="page min-h-full bg-bg"><header className="flex items-center justify-between px-5 pt-[14px]"><button onClick={()=>setMonthOffset(x=>x-1)} className="px-2 py-1 text-xl text-t2">‹</button><b className="text-[22px] font-black tracking-[-.5px] text-t1">{label}</b><div className="flex items-center gap-1"><button onClick={()=>setMonthOffset(x=>x+1)} className="px-2 py-1 text-xl text-t2">›</button><button onClick={()=>setHorizon(true)} className="grid h-7 w-8 place-items-center rounded-lg border border-border bg-el text-t2"><CalendarRange size={16}/></button></div></header>
 <div className="sticky top-0 z-20 mt-[10px] grid grid-cols-4 border-b border-border bg-bg/95 backdrop-blur">{(['saldos','totais','tags','menu'] as FluxTab[]).map(x=><button onClick={()=>setTab(x)} key={x} className={cn('border-b-2 border-transparent py-[10px] text-xs font-semibold text-t3 transition',tab===x&&'border-flux text-flux')}>{x}</button>)}</div>
 <div className={cn('pb-6',tab!=='saldos'&&'px-4 pt-4')}>{tab==='saldos'&&<Saldos month={base}/>} {tab==='totais'&&<Totais monthKey={key}/>} {tab==='tags'&&<Tags monthKey={key}/>} {tab==='menu'&&<FluxMenu/>}</div>
 {tab==='saldos'&&<button onClick={()=>setAdding(true)} className="fixed bottom-[96px] left-1/2 z-30 grid h-14 w-14 -translate-x-1/2 place-items-center rounded-full bg-flux text-white shadow-[0_10px_35px_#ff6b3560] transition active:scale-95"><Plus size={24}/></button>}
 {horizon&&<Horizon close={()=>setHorizon(false)}/>} {adding&&<NewTransaction close={()=>setAdding(false)}/>}</div>
}

function Saldos({month}:{month:Date}){const data=useFinancas(s=>s.data);const currentKey=monthKey(month);const nextDate=new Date(month.getFullYear(),month.getMonth()+1,1);const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();const nowDay=17;let balance=data.perfil.saldo_inicial; const rows=Array.from({length:days},(_,i)=>{const day=i+1;const date=`${currentKey}-${String(day).padStart(2,'0')}`;const tx=data.flux.lancamentos.filter(l=>l.data===date);tx.forEach(l=>balance+=l.tipo==='entrada'?l.valor:-l.valor);const curr=balance;const projected=curr+(data.flux.lancamentos.filter(l=>l.data.startsWith(monthKey(nextDate))).reduce((a,l)=>a+(l.tipo==='entrada'?l.valor:-l.valor),0))-data.flux.valor_diario_planejado*Math.max(0,day-nowDay);return{day,date,tx,curr,projected}})
 return <Card className="overflow-hidden"><div className="grid grid-cols-[42px_1fr_72px_72px] border-b border-border bg-el/60 px-2 py-3 text-[8px] font-bold uppercase tracking-wider text-t3"><span>Dia</span><span>Transações</span><span className="text-right">{new Intl.DateTimeFormat('pt-BR',{month:'short',year:'2-digit'}).format(month)}</span><span className="text-right opacity-60">{new Intl.DateTimeFormat('pt-BR',{month:'short',year:'2-digit'}).format(nextDate)}</span></div>{rows.map(row=>{const date=new Date(`${row.date}T12:00:00`);const week=new Intl.DateTimeFormat('pt-BR',{weekday:'short'}).format(date).replace('.','');return <div key={row.date} className={cn('grid min-h-12 grid-cols-[42px_1fr_72px_72px] items-center border-b border-border/60 px-2 py-2 last:border-0',row.day===nowDay&&'bg-flux/5')}><div><b className={cn('number text-xs',row.day===nowDay&&'text-flux')}>{String(row.day).padStart(2,'0')}</b><p className="mt-0.5 text-[8px] text-t3">{week}</p></div><div className="min-w-0 space-y-1">{row.tx.length?row.tx.map(tx=><div key={tx.id} className="flex min-w-0 items-center gap-1.5"><span className="grid h-4 w-4 shrink-0 place-items-center rounded text-[8px] font-bold" style={{color:fluxMeta[tx.tipo].color,background:`${fluxMeta[tx.tipo].color}18`}}>{fluxMeta[tx.tipo].icon}</span><span className="truncate text-[9px] text-t2">{tx.descricao}</span></div>):row.day>nowDay?<div className="flex items-center gap-1.5"><span className="grid h-4 w-4 place-items-center rounded border border-dashed border-pink-400 text-[7px] text-pink-400">:D</span><span className="flex items-baseline gap-1 text-[8px] text-t3">prev. <Currency value={data.flux.valor_diario_planejado}/></span></div>:null}</div><b className="number text-right text-[8px]" style={{color:saldoTemperature(row.curr)}}>{money(row.curr)}</b><b className="number text-right text-[8px] opacity-60" style={{color:saldoTemperature(row.projected)}}>{money(row.projected)}</b></div>})}</Card>}

function Totais({monthKey:key}:{monthKey:string}){const data=useFinancas(s=>s.data);const tx=data.flux.lancamentos.filter(l=>l.data.startsWith(key));const sums=(type:FluxTipo)=>tx.filter(l=>l.tipo===type).reduce((a,b)=>a+b.valor,0);const entrada=sums('entrada'),saida=sums('saida'),diario=sums('diario'),economia=sums('economia'),cartao=sums('cartao');const perf=entrada-saida-diario-economia-cartao;const rate=entrada?economia/entrada*100:0;const daysPassed=Math.max(1,17);const remaining=Math.max(0,new Date(Number(key.slice(0,4)),Number(key.slice(5,7)),0).getDate()-daysPassed)
return <div className="space-y-4"><Card className="p-5"><p className="text-[10px] text-t3">Performance do mês</p><Currency value={perf} className={cn('mt-2 text-[34px] font-bold',perf>=0?'text-green':'text-red')}/><p className="mt-2 text-[9px] text-t3">entradas − saídas − diário − economia − cartão</p></Card><div className="grid grid-cols-2 gap-3"><Card className="p-4"><p className="text-[9px] text-t3">Economizado</p><p className="number mt-2 text-lg font-bold text-green">{rate.toFixed(1)}%</p><div className="mt-3 h-1 rounded bg-el"><div className="h-full rounded bg-green" style={{width:`${Math.min(100,rate)}%`}}/></div></Card><Card className="p-4"><p className="text-[9px] text-t3">Custo de vida</p><Currency value={saida+diario+cartao} className="mt-2 text-lg font-bold"/><p className="mt-2 flex items-baseline gap-1 text-[8px] text-t3">média diária <Currency value={diario/daysPassed}/></p></Card></div><Card className="p-4"><p className="mb-4 text-xs font-semibold">Movimentações do mês</p>{(Object.keys(fluxMeta) as FluxTipo[]).map(type=><div key={type} className="mb-3 flex items-center last:mb-0"><span className="mr-3 grid h-7 w-7 place-items-center rounded-lg text-xs font-bold" style={{color:fluxMeta[type].color,background:`${fluxMeta[type].color}18`}}>{fluxMeta[type].icon}</span><span className="flex-1 text-[10px] text-t2">{fluxMeta[type].label}</span><Currency value={sums(type)} className="text-xs font-bold"/></div>)}</Card><Card className="border-dashed border-flux/40 p-4"><div className="flex justify-between"><span className="text-[10px] text-t2">Previsão de diários</span><Currency value={remaining*data.flux.valor_diario_planejado} className="text-xs font-bold text-flux"/></div><p className="mt-2 flex items-baseline gap-1 text-[8px] text-t3">{remaining} dias restantes × <Currency value={data.flux.valor_diario_planejado}/></p></Card></div>}

function Tags({monthKey:key}:{monthKey:string}){const data=useFinancas(s=>s.data);const [search,setSearch]=useState('');return <div><div className="relative mb-4"><Search className="absolute left-3 top-3 text-t3" size={15}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Filtrar tags" className="pl-9 focus:border-flux"/></div><Card className="overflow-hidden">{data.flux.tags.filter(t=>t.label.toLowerCase().includes(search.toLowerCase())).map(tag=>{const total=data.flux.lancamentos.filter(l=>l.data.startsWith(key)&&l.tag_id===tag.id).reduce((a,b)=>a+b.valor,0);return <div key={tag.id} className="flex items-center border-b border-border px-4 py-4 last:border-0"><span className="mr-3 grid h-9 w-9 place-items-center rounded-xl text-sm" style={{color:tag.cor,background:`${tag.cor}18`}}>⌑</span><div className="flex-1"><p className="text-xs font-semibold">{tag.label}</p><p className="mt-1 text-[9px] text-t3">Total do mês</p></div><Currency value={total} className="text-xs font-bold" style={{color:tag.cor}}/></div>})}</Card></div>}
function FluxMenu(){const {data,mutate}=useFinancas();return <div className="space-y-3"><Card className="p-4"><p className="text-xs font-semibold">Planejamento diário</p><p className="mt-1 text-[9px] text-t3">Valor usado nas previsões futuras</p><MoneyInput value={data.flux.valor_diario_planejado} onValueChange={value=>mutate(d=>{d.flux.valor_diario_planejado=value})} className="number mt-4 focus-within:border-flux"/></Card><Card className="p-4"><p className="text-xs font-semibold">Temperatura do saldo</p><div className="mt-4 grid grid-cols-4 gap-1 text-center text-[7px]">{[['< 0,00','#EF4444'],['0,00–499,00','#FBBF24'],['500,00–1.999,00','#86EFAC'],['2.000,00+','#34D399']].map(([l,c])=><div key={l}><span className="mx-auto mb-2 block h-3 w-3 rounded-full" style={{background:c}}/>{l}</div>)}</div></Card></div>}

function Horizon({close}:{close:()=>void}){const data=useFinancas(s=>s.data);const months=Array.from({length:6},(_,i)=>new Date(2026,6+i,1));const days=Array.from({length:31},(_,i)=>i+1);let running=data.perfil.saldo_inicial;return <div className="absolute inset-0 z-50 overflow-auto bg-bg"><header className="safe-top sticky top-0 z-10 flex items-center justify-between border-b border-border bg-bg/95 px-5 pb-4 backdrop-blur"><div><p className="text-[10px] font-bold uppercase tracking-wider text-flux">Horizonte</p><h2 className="mt-1 text-lg font-bold">Saldos futuros</h2></div><button onClick={close} className="grid h-9 w-9 place-items-center rounded-full bg-el"><X size={16}/></button></header><div className="min-w-[650px] p-5"><div className="grid grid-cols-[42px_repeat(6,92px)] gap-1 text-center text-[9px] font-bold uppercase text-t3"><span>Dia</span>{months.map(m=><span key={String(m)}>{new Intl.DateTimeFormat('pt-BR',{month:'short',year:'2-digit'}).format(m)}</span>)}</div>{days.map(day=><div key={day} className="mt-1 grid grid-cols-[42px_repeat(6,92px)] gap-1"><span className="py-2 text-center text-[9px] text-t3">{day}</span>{months.map(m=>{const date=`${monthKey(m)}-${String(day).padStart(2,'0')}`;data.flux.lancamentos.filter(l=>l.data===date).forEach(l=>running+=l.tipo==='entrada'?l.valor:-l.valor);const color=saldoTemperature(running);return <span key={date} className="rounded-lg py-2 text-center text-[8px] font-semibold" style={{color,background:`${color}12`}}>{money(running)}</span>})}</div>)}</div></div>}

function NewTransaction({close}:{close:()=>void}){const {data,mutate}=useFinancas();const [type,setType]=useState<FluxTipo>('saida');const [desc,setDesc]=useState('');const [value,setValue]=useState(0);const [tag,setTag]=useState('');return <div className="absolute inset-0 z-50 flex items-end bg-black/70"><div className="safe-bottom w-full rounded-t-[28px] border-t border-border bg-surface p-5"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">Nova movimentação</h2><button onClick={close} className="p-2 text-t3"><X size={18}/></button></div><div className="mb-4 flex gap-2 overflow-x-auto">{(Object.keys(fluxMeta) as FluxTipo[]).map(x=><button key={x} onClick={()=>setType(x)} className="shrink-0 rounded-full border px-3 py-2 text-[9px] font-semibold" style={{borderColor:type===x?fluxMeta[x].color:'var(--border)',color:type===x?fluxMeta[x].color:'var(--t2)'}}>{fluxMeta[x].icon} {fluxMeta[x].label}</button>)}</div><div className="space-y-2"><Input placeholder="Descrição" value={desc} onChange={e=>setDesc(e.target.value)} className="focus:border-flux"/><MoneyInput aria-label="Valor" value={value} onValueChange={setValue} className="focus-within:border-flux"/><select value={tag} onChange={e=>setTag(e.target.value)} className="h-11 w-full rounded-xl border border-border bg-el px-3 text-sm text-t2 outline-none"><option value="">Sem tag</option>{data.flux.tags.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></div><button disabled={!desc||!value} onClick={()=>{mutate(d=>d.flux.lancamentos.push({id:uid(),data:new Date().toISOString().slice(0,10),tipo:type,valor:value,descricao:desc,tag_id:tag||null}));close()}} className="mt-4 h-12 w-full rounded-xl bg-flux text-sm font-bold text-white disabled:opacity-40">Adicionar</button></div></div>}
