import { useState } from 'react'
import { IconChevronRight as ChevronRight } from '@tabler/icons-react'
import { PageHeader } from '../components/PageHeader'
import { SunriseHero } from '../components/SunriseHero'
import { SubscriptionEditor, SubscriptionLogo } from '../components/SubscriptionLogo'
import { AddButton, DangerButton, MoneyInput } from '../components/ui'
import { Currency } from '../components/Currency'
import { catColors, cn, sum, totals, uid } from '../lib/utils'
import { useFinancas } from '../store/use-financas'
import type { FinancasData, Item } from '../lib/types'

type Category=keyof FinancasData['tabela']
const sections:{key:Category;label:string;color:string}[]=[{key:'entradas',label:'Entradas',color:catColors.entradas},{key:'fixos',label:'Gastos Fixos',color:catColors.fixos},{key:'variaveis',label:'Gastos Variáveis',color:catColors.variaveis},{key:'assinaturas',label:'Assinaturas',color:catColors.assinaturas}]

export function Tabela(){const {data,mutate}=useFinancas();const t=totals(data);return <div className="pb-4"><PageHeader eyebrow="Planejamento" title="Entradas e Gastos" subtitle="toque em qualquer item para ver projeção"/><SunriseHero label="Resultado mensal" value={<Currency value={t.saldo}/>} caption={<><Currency value={t.entradas}/> entradas <span>–</span> <Currency value={t.gastos}/> gastos <span>–</span> <Currency value={data.perfil.economia_mensal}/> economia</>} kpis={[{label:'Entradas',value:<Currency value={t.entradas}/>,sub:`${data.tabela.entradas.length} fontes`,className:'text-green'},{label:'Total gastos',value:<Currency value={t.gastos}/>,sub:`${t.entradas?(t.gastos/t.entradas*100).toFixed(1).replace('.',','):0}% da renda`,className:'text-red'},{label:'Economia',value:<Currency value={data.perfil.economia_mensal}/>,sub:'comprometida',className:'text-green'}]}/>{sections.map(s=><BudgetSection key={s.key} section={s} items={data.tabela[s.key]}/>)}<section className="mx-4 mb-[10px]"><p className="flex items-center px-[14px] pb-1 pt-1.5 text-[10px] font-extrabold uppercase tracking-[1px] text-t3"><i className="mark-diamond"/>Economia</p><div className="card-glow flex items-center justify-between rounded-[14px] border border-border bg-surface px-4 py-[14px]"><div><p className="mb-1 text-[11px] font-semibold text-t3">Economia mensal comprometida</p><MoneyInput value={data.perfil.economia_mensal} onValueChange={value=>mutate(d=>{d.perfil.economia_mensal=value})} className="number h-auto w-40 border-0 bg-transparent p-0 text-[26px] font-black tracking-[-1.5px] outline-none" style={{color:catColors.economia}}/><p className="mt-1 text-[10px] text-t3">esse valor alimenta automaticamente a aba Economia</p></div></div></section><Result data={data} totals={t}/></div>}

function BudgetSection({section,items}:{section:typeof sections[number];items:Item[]}){
 const mutate=useFinancas(s=>s.mutate);const [expanded,setExpanded]=useState<string|null>(null)
 const addItem=()=>{const id=uid();mutate(d=>d.tabela[section.key].push({id,label:section.key==='assinaturas'?'':'Novo item',valor:0}));setExpanded(id)}
 return <section className="mx-4 mb-2"><div className="flex items-center justify-between px-[14px] pb-1.5 pt-2 text-[10px] font-extrabold uppercase tracking-[1px] text-t3"><span className="flex items-center"><i className="mark-diamond"/>{section.label}</span><AddButton onClick={addItem}/></div><div className="card-glow overflow-hidden rounded-[14px] border border-border bg-surface">{items.map(item=><div key={item.id}><button onClick={()=>setExpanded(expanded===item.id?null:item.id)} className="flex w-full items-center justify-between border-b border-border px-[14px] py-3 text-left"><span className="flex items-center gap-2 text-sm text-t1">{section.key==='assinaturas'&&<SubscriptionLogo item={item} size={28}/>} {item.label||'Nova assinatura'}</span><span className="flex items-center"><Currency value={item.valor} className="text-sm font-bold" style={{color:section.color}}/><ChevronRight size={14} className={cn('ml-1.5 text-t3 transition',expanded===item.id&&'rotate-90')}/></span></button>{expanded===item.id&&<div className="border-b border-border py-1.5" style={{background:`${section.color}0A`}}>{section.key==='assinaturas'&&<SubscriptionEditor item={item}/>}<p className="px-[14px] pb-0.5 pt-1 text-[9px] font-bold uppercase tracking-[.8px] text-t3">{section.key==='entradas'?'Se manter esse valor, você vai acumular':'Custo acumulado'}</p>{[[3,'3 meses'],[6,'6 meses'],[12,'1 ano'],[24,'2 anos'],[60,'5 anos']].map(([n,l])=><div key={String(l)} className="flex justify-between border-b border-border/50 px-[22px] py-[7px] last:border-0"><span className="text-xs text-t2">{l}</span><Currency value={item.valor*Number(n)} className="text-[13px] font-bold" style={{color:section.color}}/></div>)}<div className="flex justify-end px-[14px] py-2"><DangerButton aria-label={`Excluir ${item.label||'item'}`} onClick={()=>mutate(d=>{d.tabela[section.key]=d.tabela[section.key].filter(x=>x.id!==item.id)})}>Excluir item</DangerButton></div></div>}</div>)}<div className="flex justify-between bg-el px-[14px] py-[9px] text-[11px] font-bold text-t2"><span>Total {section.label.toLowerCase()}</span><Currency value={sum(items)} style={{color:section.color}}/></div></div></section>
}

function Result({data,totals:t}:{data:FinancasData;totals:ReturnType<typeof totals>}){const rows=[['Entradas',t.entradas,catColors.entradas],['Gastos fixos',t.fixos,catColors.fixos],['Gastos variáveis',t.variaveis,catColors.variaveis],['Assinaturas',t.assinaturas,catColors.assinaturas],['Economia',data.perfil.economia_mensal,catColors.economia]] as const;return <section className="card-glow mx-4 mb-2 mt-[10px] overflow-hidden rounded-[16px] border border-border bg-surface p-3"><div className="mb-4 flex items-center px-1 pt-1"><p className="flex items-center text-[10px] font-extrabold uppercase tracking-[1px] text-t3"><i className="mark-diamond"/>Resultado mensal</p></div><div className="px-1">{rows.map(([l,v,c])=><div key={l} className="mb-[11px] flex items-center gap-2"><span className="w-[128px] text-xs text-t2">{l}</span><span className="h-[5px] flex-1 overflow-hidden rounded-full bg-el"><i className="block h-full rounded-full" style={{width:`${Math.min(100,t.entradas?v/t.entradas*100:0)}%`,background:c}}/></span><span className="number flex w-[94px] shrink-0 items-center justify-end gap-1 text-right"><Currency value={v} className="text-xs font-bold" style={{color:c}}/><i className="h-3 w-px bg-border"/><small className="text-[9px] not-italic text-t3">{t.entradas?(v/t.entradas*100).toFixed(0):0}%</small></span></div>)}</div></section>}
