import { useState } from 'react'
import { IconBell as Bell, IconChevronRight as ChevronRight } from '@tabler/icons-react'
import { AurvmDatePicker } from '../components/AurvmControls'
import { PageHeader } from '../components/PageHeader'
import { SunriseHero } from '../components/SunriseHero'
import { SubscriptionEditor, SubscriptionLogo } from '../components/SubscriptionLogo'
import { AddButton, Button, DangerButton, Input, MoneyInput } from '../components/ui'
import { Currency } from '../components/Currency'
import { catColors, cn, sum, totals, uid } from '../lib/utils'
import { useFinancas } from '../store/use-financas'
import type { FinancasData, Item } from '../lib/types'

type Category=keyof FinancasData['tabela']
const sections:{key:Category;label:string;color:string}[]=[{key:'entradas',label:'Entradas',color:catColors.entradas},{key:'fixos',label:'Gastos Fixos',color:catColors.fixos},{key:'variaveis',label:'Gastos Variáveis',color:catColors.variaveis},{key:'assinaturas',label:'Assinaturas',color:catColors.assinaturas}]

export function Tabela(){
 const {data,mutate}=useFinancas();const t=totals(data)
 return <div className="pb-4"><PageHeader eyebrow="Planejamento" title="Entradas e Gastos" subtitle="toque em qualquer item para ver projeção"/><SunriseHero label="Resultado mensal" value={<Currency value={t.saldo}/>} caption={<><Currency value={t.entradas}/> entradas <span>–</span> <Currency value={t.gastos}/> gastos <span>–</span> <Currency value={data.perfil.economia_mensal}/> economia</>} kpis={[{label:'Entradas',value:<Currency value={t.entradas}/>,sub:`${data.tabela.entradas.length} fontes`,className:'text-green'},{label:'Total gastos',value:<Currency value={t.gastos}/>,sub:`${t.entradas?(t.gastos/t.entradas*100).toFixed(1).replace('.',','):0}% da renda`,className:'text-red'},{label:'Economia',value:<Currency value={data.perfil.economia_mensal}/>,sub:'comprometida',className:'text-green'}]}/>{sections.map(s=><BudgetSection key={s.key} section={s} items={data.tabela[s.key]}/>)}
  <section className="mx-4 mb-[10px]"><p className="flex items-center px-[14px] pb-1 pt-1.5 text-[10px] font-extrabold uppercase tracking-[1px] text-t3"><i className="mark-diamond"/>Economia</p><div className="card-glow rounded-[14px] border border-border bg-surface p-4"><div className="mb-2"><p className="text-[11px] font-semibold text-t2">Economia mensal comprometida</p><p className="mt-0.5 text-[9px] text-t3">toque no valor para editar</p></div><MoneyInput aria-label="Economia mensal comprometida" value={data.perfil.economia_mensal} onValueChange={value=>mutate(d=>{d.perfil.economia_mensal=value})} className="h-12 w-full rounded-[12px] border-green/20 bg-green/[.06] px-3 text-[24px] font-black tracking-[-1.2px] focus-within:border-green" inputClassName="text-right" style={{color:catColors.economia}}/><p className="mt-2 text-[9px] text-t3">Esse valor alimenta automaticamente a aba Economia.</p></div></section><Result data={data} totals={t}/></div>
}

function BudgetSection({section,items}:{section:typeof sections[number];items:Item[]}){
 const mutate=useFinancas(s=>s.mutate);const [expanded,setExpanded]=useState<string|null>(null)
 const addItem=()=>{const id=uid();mutate(d=>d.tabela[section.key].push({id,label:section.key==='assinaturas'?'':'Novo item',valor:0}));setExpanded(id)}
 return <section className="mx-4 mb-2"><div className="flex items-center justify-between px-[14px] pb-1.5 pt-2 text-[10px] font-extrabold uppercase tracking-[1px] text-t3"><span className="flex items-center"><i className="mark-diamond"/>{section.label}</span><AddButton onClick={addItem}/></div><div className="card-glow overflow-hidden rounded-[14px] border border-border bg-surface">{items.map(item=><div key={item.id}><button onClick={()=>setExpanded(expanded===item.id?null:item.id)} className="flex w-full items-center justify-between border-b border-border px-[14px] py-3 text-left"><span className="flex items-center gap-2 text-sm text-t1">{section.key==='assinaturas'&&<SubscriptionLogo item={item} size={28}/>} {item.label||'Nova assinatura'}</span><span className="flex items-center"><Currency value={item.valor} className="text-sm font-bold" style={{color:section.color}}/><ChevronRight size={14} className={cn('ml-1.5 text-t3 transition',expanded===item.id&&'rotate-90')}/></span></button>{expanded===item.id&&<div className="border-b border-border py-1.5" style={{background:`${section.color}0A`}}>{section.key==='assinaturas'&&<SubscriptionEditor item={item}/>}<BudgetItemEditor section={section} item={item}/><p className="px-[14px] pb-0.5 pt-2 text-[9px] font-bold uppercase tracking-[.8px] text-t3">{section.key==='entradas'?'Se manter esse valor, você vai acumular':'Custo acumulado'}</p>{[[3,'3 meses'],[6,'6 meses'],[12,'1 ano'],[24,'2 anos'],[60,'5 anos']].map(([n,l])=><div key={String(l)} className="flex justify-between border-b border-border/50 px-[22px] py-[7px] last:border-0"><span className="text-xs text-t2">{l}</span><Currency value={item.valor*Number(n)} className="text-[13px] font-bold" style={{color:section.color}}/></div>)}</div>}</div>)}<div className="flex justify-between bg-el px-[14px] py-[9px] text-[11px] font-bold text-t2"><span>Total {section.label.toLowerCase()}</span><Currency value={sum(items)} style={{color:section.color}}/></div></div></section>
}

function BudgetItemEditor({section,item}:{section:typeof sections[number];item:Item}){
 const mutate=useFinancas(s=>s.mutate)
 const [reminderOpen,setReminderOpen]=useState(false)
 const [reminderDate,setReminderDate]=useState(item.lembrete?.data??new Date().toISOString().slice(0,10))
 const [reminderNote,setReminderNote]=useState(item.lembrete?.observacao??'')
 const update=(change:(target:Item)=>void)=>mutate(d=>{const target=d.tabela[section.key].find(entry=>entry.id===item.id);if(target)change(target)})
 return <div className="border-b border-border/60 px-[14px] py-3">
  {section.key!=='assinaturas'&&<label className="block min-w-0"><span className="mb-1 block text-[8px] font-bold uppercase tracking-[.7px] text-t3">Nome</span><input aria-label={`Nome de ${item.label||'item'}`} value={item.label} onChange={event=>update(target=>{target.label=event.target.value})} className="h-9 w-full rounded-[11px] border border-border bg-surface px-3 text-xs font-semibold text-t1 outline-none transition focus:border-accent"/></label>}
  <div className={cn('flex items-end gap-2',section.key!=='assinaturas'&&'mt-2')}><label className="min-w-0 flex-1"><span className="mb-1 block text-[8px] font-bold uppercase tracking-[.7px] text-t3">Valor mensal</span><MoneyInput aria-label={`Valor de ${item.label||'item'}`} value={item.valor} onValueChange={value=>update(target=>{target.valor=value})} className="h-9 rounded-[11px] bg-surface px-2.5 text-xs font-bold" inputClassName="text-right" style={{color:section.color}}/></label><button aria-label={item.lembrete?'Editar lembrete':'Adicionar lembrete'} title={item.lembrete?'Editar lembrete':'Adicionar lembrete'} onClick={()=>setReminderOpen(value=>!value)} className={cn('glass-action glass-yellow grid h-9 w-9 shrink-0 place-items-center rounded-[11px] border transition active:scale-95',item.lembrete&&'ring-1 ring-yellow/20')}><Bell size={14}/></button><DangerButton className="h-9 w-9 rounded-[11px]" aria-label={`Excluir ${item.label||'item'}`} onClick={()=>mutate(d=>{d.tabela[section.key]=d.tabela[section.key].filter(x=>x.id!==item.id)})}/></div>
  {item.lembrete&&<div className="mt-2 flex items-start gap-2 rounded-[11px] border border-yellow/20 bg-yellow/[.07] px-2.5 py-2 text-yellow"><Bell size={13} className="mt-0.5 shrink-0"/><div className="min-w-0"><p className="text-[9px] font-bold">Lembrar em {new Date(`${item.lembrete.data}T12:00:00`).toLocaleDateString('pt-BR')}</p>{item.lembrete.observacao&&<p className="mt-0.5 truncate text-[8px] text-t2">{item.lembrete.observacao}</p>}</div></div>}
  {reminderOpen&&<div className="mt-2 rounded-[13px] border border-yellow/20 bg-surface p-3"><div className="mb-2 flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-[9px] bg-yellow/10 text-yellow"><Bell size={13}/></span><div><p className="text-[10px] font-bold text-t1">Lembrete</p><p className="text-[8px] text-t3">Defina quando deseja lembrar.</p></div></div><AurvmDatePicker value={reminderDate} onChange={setReminderDate} accentColor="var(--yellow)" className="h-9 w-full justify-between bg-el/50 px-3"/><Input aria-label="Observação do lembrete" placeholder="Observação opcional" value={reminderNote} onChange={event=>setReminderNote(event.target.value)} className="mt-2 h-9 bg-el/50 text-xs"/><div className="mt-2 flex items-center justify-end gap-2">{item.lembrete&&<DangerButton aria-label="Remover lembrete" title="Remover lembrete" onClick={()=>{update(target=>{target.lembrete=null});setReminderOpen(false)}}/>}<button onClick={()=>setReminderOpen(false)} className="h-8 rounded-[10px] px-2.5 text-[9px] font-semibold text-t2">Cancelar</button><Button disabled={!reminderDate} onClick={()=>{update(target=>{target.lembrete={data:reminderDate,observacao:reminderNote.trim()}});setReminderOpen(false)}} className="h-8 rounded-[10px] bg-yellow px-3 text-[9px]">Salvar</Button></div></div>}
 </div>
}

function Result({data,totals:t}:{data:FinancasData;totals:ReturnType<typeof totals>}){const rows=[['Entradas',t.entradas,catColors.entradas],['Gastos fixos',t.fixos,catColors.fixos],['Gastos variáveis',t.variaveis,catColors.variaveis],['Assinaturas',t.assinaturas,catColors.assinaturas],['Economia',data.perfil.economia_mensal,catColors.economia]] as const;return <section className="card-glow mx-4 mb-2 mt-[10px] overflow-hidden rounded-[16px] border border-border bg-surface p-3"><div className="mb-4 flex items-center px-1 pt-1"><p className="flex items-center text-[10px] font-extrabold uppercase tracking-[1px] text-t3"><i className="mark-diamond"/>Resultado mensal</p></div><div className="px-1">{rows.map(([l,v,c])=><div key={l} className="mb-[11px] flex items-center gap-2"><span className="w-[128px] text-xs text-t2">{l}</span><span className="h-[5px] flex-1 overflow-hidden rounded-full bg-el"><i className="block h-full rounded-full" style={{width:`${Math.min(100,t.entradas?v/t.entradas*100:0)}%`,background:c}}/></span><span className="number flex w-[94px] shrink-0 items-center justify-end gap-1 text-right"><Currency value={v} className="text-xs font-bold" style={{color:c}}/><i className="h-3 w-px bg-border"/><small className="text-[9px] not-italic text-t3">{t.entradas?(v/t.entradas*100).toFixed(0):0}%</small></span></div>)}</div></section>}
