import { useState } from 'react'
import { IconChevronRight as ChevronRight } from '@tabler/icons-react'
import { PageHeader } from '../components/PageHeader'
import { SubscriptionEditor, SubscriptionLogo } from '../components/SubscriptionLogo'
import { AddButton, MoneyInput } from '../components/ui'
import { Currency } from '../components/Currency'
import { brl, cn, sum, totals, uid } from '../lib/utils'
import { useFinancas } from '../store/use-financas'
import type { FinancasData, Item } from '../lib/types'

type Category=keyof FinancasData['tabela']
const sections:{key:Category;label:string;color:string}[]=[{key:'entradas',label:'Entradas',color:'#20A968'},{key:'fixos',label:'Gastos Fixos',color:'#EF4444'},{key:'variaveis',label:'Gastos Variáveis',color:'#FB923C'},{key:'assinaturas',label:'Assinaturas',color:'#FBBF24'}]

export function Tabela(){const {data,mutate}=useFinancas();const t=totals(data);return <div className="pb-4"><PageHeader title="Entradas e Gastos" subtitle="toque em qualquer item para ver projeção"/>{sections.map(s=><BudgetSection key={s.key} section={s} items={data.tabela[s.key]}/>)}<section className="mx-4 mb-[10px]"><p className="px-[14px] pb-1 pt-1.5 text-[10px] font-extrabold uppercase tracking-[1px] text-t3">Economia</p><div className="flex items-center justify-between rounded-[14px] border bg-surface px-4 py-[14px]" style={{borderColor:'#20A96866'}}><div><p className="mb-1 text-[11px] font-semibold text-t3">Economia mensal comprometida</p><MoneyInput value={data.perfil.economia_mensal} onValueChange={value=>mutate(d=>{d.perfil.economia_mensal=value})} className="number h-auto w-40 border-0 bg-transparent p-0 text-[26px] font-black tracking-[-1.5px] outline-none" style={{color:'#20A968'}}/><p className="mt-1 text-[10px] text-t3">esse valor alimenta automaticamente a aba Economia</p></div></div></section><Result data={data} totals={t}/></div>}

function BudgetSection({section,items}:{section:typeof sections[number];items:Item[]}){
 const mutate=useFinancas(s=>s.mutate);const [expanded,setExpanded]=useState<string|null>(null)
 const addItem=()=>{const id=uid();mutate(d=>d.tabela[section.key].push({id,label:section.key==='assinaturas'?'':'Novo item',valor:0}));setExpanded(id)}
 return <section className="mx-4 mb-2"><div className="flex items-center justify-between px-[14px] pb-1.5 pt-2 text-[10px] font-extrabold uppercase tracking-[1px] text-t3"><span>{section.label}</span><AddButton color={section.color} onClick={addItem}/></div><div className="overflow-hidden rounded-[14px] border border-border bg-surface">{items.map(item=><div key={item.id}><button onClick={()=>setExpanded(expanded===item.id?null:item.id)} className="flex w-full items-center justify-between border-b border-border px-[14px] py-3 text-left"><span className="flex items-center gap-2 text-sm text-t1">{section.key==='assinaturas'&&<SubscriptionLogo item={item} size={28}/>} {item.label||'Nova assinatura'}</span><span className="flex items-center"><Currency value={item.valor} className="text-sm font-bold" style={{color:section.color}}/><ChevronRight size={14} className={cn('ml-1.5 text-t3 transition',expanded===item.id&&'rotate-90')}/></span></button>{expanded===item.id&&<div className="border-b border-border py-1.5" style={{background:`${section.color}0A`}}>{section.key==='assinaturas'&&<SubscriptionEditor item={item}/>}<p className="px-[14px] pb-0.5 pt-1 text-[9px] font-bold uppercase tracking-[.8px] text-t3">{section.key==='entradas'?'Se manter esse valor, você vai acumular':'Custo acumulado'}</p>{[[3,'3 meses'],[6,'6 meses'],[12,'1 ano'],[24,'2 anos'],[60,'5 anos']].map(([n,l])=><div key={String(l)} className="flex justify-between border-b border-border/50 px-[22px] py-[7px] last:border-0"><span className="text-xs text-t2">{l}</span><Currency value={item.valor*Number(n)} className="text-[13px] font-bold" style={{color:section.color}}/></div>)}</div>}</div>)}<div className="flex justify-between bg-el px-[14px] py-[9px] text-[11px] font-bold text-t2"><span>Total {section.label.toLowerCase()}</span><Currency value={sum(items)} style={{color:section.color}}/></div></div></section>
}

function Result({data,totals:t}:{data:FinancasData;totals:ReturnType<typeof totals>}){const rows=[['Entradas',t.entradas,'#20A968'],['Gastos fixos',t.fixos,'#EF4444'],['Gastos variáveis',t.variaveis,'#FB923C'],['Assinaturas',t.assinaturas,'#FBBF24'],['Economia',data.perfil.economia_mensal,'#20A968']] as const;return <section className="mx-4 mb-2 mt-[10px] overflow-hidden rounded-[16px] border border-border bg-surface p-3 shadow-[0_8px_28px_rgba(70,45,32,.05)]"><div className="mb-4 flex items-center gap-2 px-1 pt-1"><i className="h-4 w-1 rounded-full bg-accent"/><p className="text-[10px] font-extrabold uppercase tracking-[1px] text-t3">Resultado mensal</p></div><div className="px-1">{rows.map(([l,v,c])=><div key={l} className="mb-[11px] flex items-center gap-2"><span className="w-[128px] text-xs text-t2">{l}</span><span className="h-[5px] flex-1 overflow-hidden rounded-full bg-el"><i className="block h-full rounded-full" style={{width:`${Math.min(100,t.entradas?v/t.entradas*100:0)}%`,background:c}}/></span><span className="number flex w-[94px] shrink-0 items-center justify-end gap-1 text-right"><Currency value={v} className="text-xs font-bold" style={{color:c}}/><i className="h-3 w-px bg-border"/><small className="text-[9px] not-italic text-t3">{t.entradas?(v/t.entradas*100).toFixed(0):0}%</small></span></div>)}</div><div className="mt-4 flex items-center justify-between rounded-[13px] border border-accent/15 px-3 py-3" style={{background:'linear-gradient(135deg,color-mix(in srgb,var(--accent) 10%,var(--surface)),var(--surface) 72%)'}}><div><p className="text-[13px] font-semibold text-t1">Saldo disponível</p><p className="mt-0.5 text-[10px] font-medium text-t3">após economia</p></div><Currency value={t.saldo} className="text-[22px] font-black tracking-[-1px] text-t1"/></div></section>}
